---
- name: Change /etc/hosts
  hosts: all
  become: True
  roles:
    - role: hosts
      ip: 192.168.50.5
      dns: mailserver.local

- name: Setup server
  become: True
  hosts: mailserver
  roles:
    - role: postfix
      allowed_networks: "192.168.50.0/24, 10.0.2.0/24"
    - role: dovecot
      user: vagrant
      password: password
